export const DELETE_CAR_DIALOGUE:'DELETE_CAR_DIALOGUE'='DELETE_CAR_DIALOGUE';
export type DELETE_CAR_DIALOGUE = typeof DELETE_CAR_DIALOGUE;
export const EDIT_CAR_DIALOGUE:'EDIT_CAR_DIALOGUE'='EDIT_CAR_DIALOGUE';
export type EDIT_CAR_DIALOGUE = typeof EDIT_CAR_DIALOGUE;
export const NEW_CAR_DIALOGUE:'NEW_CAR_DIALOGUE'='NEW_CAR_DIALOGUE';
export type NEW_CAR_DIALOGUE = typeof NEW_CAR_DIALOGUE;
export const CAR_DETAILS_DIALOGUE:'CAR_DETAILS_DIALOGUE'='CAR_DETAILS_DIALOGUE';
export type CAR_DETAILS_DIALOGUE = typeof CAR_DETAILS_DIALOGUE;

export type Dialogue =
CAR_DETAILS_DIALOGUE | DELETE_CAR_DIALOGUE | EDIT_CAR_DIALOGUE | NEW_CAR_DIALOGUE | null;
